import React, { useEffect, useMemo, useState } from 'react';
import { Bot, Send, Sparkles, Lightbulb, RefreshCw, Zap } from 'lucide-react';
import { firebaseAuth } from '../services/firebase';
import { formatCurrency } from '../utils/formatters';

interface Props { available:number; income:number; spent:number; budget:number; upcomingBills:number; }
type Answer={title:string;body:string;tip?:string};
type Usage={success:boolean;plan:string;model:string;limit:number;used:number;remaining:number;inputTokens:number;outputTokens:number;failedRequests:number;month:string;lastUsedAt:number|null};
const DEFAULT_LIMIT=100;

const fallbackAnswer=(question:string,available:number,income:number,spent:number,budget:number,upcomingBills:number):Answer=>{
 const q=question.toLowerCase(); const savings=income>0?Math.max(0,((income-spent)/income)*100):0; const budgetLeft=budget-spent;
 if(q.includes('afford')||q.includes('buy')||q.includes('purchase')||q.includes('spend')){const safe=Math.max(0,available-upcomingBills);return{title:safe>0?'You have room, with a buffer':'This purchase looks tight',body:`You currently have ${formatCurrency(available)} available and about ${formatCurrency(upcomingBills)} in upcoming commitments. That leaves roughly ${formatCurrency(safe)} before considering this purchase.`,tip:safe>0?'Keep an emergency buffer and avoid using money already committed to bills or goals.':'Consider delaying the purchase or reducing discretionary spending first.'};}
 if(q.includes('save')||q.includes('saving'))return{title:`Your savings rate is ${savings.toFixed(0)}%`,body:income>0?`You earned ${formatCurrency(income)} and spent ${formatCurrency(spent)} in this period. That leaves about ${formatCurrency(Math.max(0,income-spent))} before other adjustments.`:'Add your income to let AHVIQ calculate meaningful savings guidance.',tip:'A consistent savings rate matters more than one unusually good month.'};
 if(q.includes('budget')||q.includes('overspend'))return{title:budget>0?(budgetLeft>=0?'Budget is under control':'Budget needs attention'):'Budget not set',body:budget>0?`You have spent ${formatCurrency(spent)} against a ${formatCurrency(budget)} budget. ${budgetLeft>=0?`${formatCurrency(budgetLeft)} remains.`:`You are ${formatCurrency(Math.abs(budgetLeft))} over budget.`}`:'Set category budgets so AHVIQ can identify overspending earlier.',tip:'Review the categories with the fastest spending growth before cutting everything equally.'};
 if(q.includes('bill')||q.includes('upcoming'))return{title:'Upcoming commitments',body:`About ${formatCurrency(upcomingBills)} is scheduled in recurring bills or commitments over the next 30 days.`,tip:'Keep committed money separate from discretionary spending when deciding what you can afford.'};
 return{title:'Your money, explained',body:`Available: ${formatCurrency(available)} · Spent: ${formatCurrency(spent)} · Savings rate: ${savings.toFixed(0)}% · Upcoming commitments: ${formatCurrency(upcomingBills)}.`,tip:'Ask a specific question and AHVIQ will use your current financial snapshot.'};
};

export const AIAdvisor:React.FC<Props>=({available,income,spent,budget,upcomingBills})=>{
 const[input,setInput]=useState(''); const[answer,setAnswer]=useState<Answer>(()=>fallbackAnswer('',available,income,spent,budget,upcomingBills)); const[loading,setLoading]=useState(false); const[error,setError]=useState(''); const[usage,setUsage]=useState<Usage|null>(null);
 const context=useMemo(()=>({available,income,spent,budget,budgetRemaining:budget-spent,upcomingBills,savingsRate:income>0?Math.max(0,((income-spent)/income)*100):0}),[available,income,spent,budget,upcomingBills]);
 const userId=firebaseAuth.currentUser?.uid||'anonymous';
 const loadUsage=async()=>{try{const r=await fetch(`/api/ai/usage?userId=${encodeURIComponent(userId)}`);if(!r.ok)return;const d=await r.json();if(d?.success)setUsage(d);}catch{}};
 useEffect(()=>{loadUsage();},[userId]);
 const ask=async(q:string)=>{const trimmed=q.trim();if(!trimmed||loading)return;setInput('');setError('');setLoading(true);try{const r=await fetch('/api/ai/advisor',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({userId,question:trimmed,context})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.success){setUsage(d?.usage||usage);throw new Error(d?.error||'AI service is unavailable.');}setAnswer({title:'AHVIQ AI says',body:d.answer,tip:'AI guidance is based on the financial snapshot currently available in AHVIQ.'});setUsage(d.usage);}catch(err:any){setError(err?.message||'AI service is unavailable.');setAnswer(fallbackAnswer(trimmed,available,income,spent,budget,upcomingBills));}finally{setLoading(false);}};
 const used=usage?.used??0; const limit=usage?.limit??DEFAULT_LIMIT; const remaining=usage?.remaining??Math.max(0,limit-used); const progress=Math.min(100,(used/Math.max(1,limit))*100);
 return <section className="rounded-2xl border border-indigo-100 bg-gradient-to-br from-indigo-50/80 via-white to-white p-4 sm:p-5 shadow-[0_1px_3px_rgba(15,23,42,0.04)]">
  <div className="flex items-start gap-3"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-indigo-600 text-white shadow-sm"><Bot className="h-5 w-5"/></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h3 className="text-sm font-bold text-slate-900">AHVIQ AI Advisor</h3><span className="inline-flex items-center gap-1 rounded-full bg-white px-2 py-1 text-[9px] font-bold text-indigo-600 ring-1 ring-indigo-100"><Sparkles className="h-3 w-3"/> Gemini AI</span></div><p className="mt-0.5 text-[11px] text-slate-500">Ask questions about your money and get answers based on your AHVIQ financial snapshot.</p></div></div>
  <div className="mt-4 rounded-xl border border-indigo-100 bg-white p-4"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2"><Zap className="h-4 w-4 text-indigo-600"/><p className="text-[11px] font-bold uppercase tracking-wide text-slate-700">AI Credits</p></div><span className="rounded-full bg-emerald-50 px-2 py-1 text-[9px] font-bold text-emerald-700">{usage?.plan||'Free'} tier</span></div><div className="mt-3 flex items-end justify-between"><div><p className="text-2xl font-black text-slate-900">{remaining}</p><p className="text-[10px] text-slate-500">credits remaining</p></div><p className="text-right text-[10px] text-slate-500">{used} used / {limit}<br/>this month</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500 transition-all" style={{width:`${progress}%`}}/></div><div className="mt-2 flex justify-between text-[9px] text-slate-400"><span>{progress.toFixed(0)}% used</span><span>{usage?.inputTokens?`${(usage.inputTokens/1000).toFixed(1)}K input tokens`:'Usage starts with your first AI question'}</span></div></div>
  <div className="mt-4 rounded-xl border border-slate-200 bg-white p-4"><div className="flex gap-3"><div className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-indigo-50 text-indigo-600"><Sparkles className="h-4 w-4"/></div><div className="min-w-0"><p className="text-sm font-bold text-slate-800">{loading?'Thinking…':answer.title}</p><p className="mt-1 whitespace-pre-line text-xs leading-5 text-slate-600">{answer.body}</p>{answer.tip&&<div className="mt-3 flex gap-2 rounded-lg bg-amber-50 p-2.5 text-[11px] text-amber-800"><Lightbulb className="h-4 w-4 shrink-0"/><span>{answer.tip}</span></div>}</div></div></div>
  {error&&<div className="mt-3 rounded-lg border border-amber-100 bg-amber-50 p-2.5 text-[10px] text-amber-800">{error}</div>}
  <div className="mt-3 flex flex-wrap gap-2">{['Can I afford a purchase?','How can I save more?','Am I over budget?','What bills are coming up?'].map(q=><button key={q} type="button" onClick={()=>ask(q)} disabled={loading||remaining<=0} className="rounded-full border border-indigo-100 bg-white px-3 py-2 text-[10px] font-semibold text-indigo-700 hover:bg-indigo-50 disabled:cursor-not-allowed disabled:opacity-40">{q}</button>)}</div>
  <form onSubmit={e=>{e.preventDefault();ask(input);}} className="mt-3 flex gap-2"><div className="relative flex-1"><input value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask AHVIQ about your money…" disabled={loading||remaining<=0} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 pr-10 text-xs outline-none focus:border-indigo-300 focus:ring-2 focus:ring-indigo-100 disabled:bg-slate-50"/><Send className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-slate-400"/></div><button type="submit" disabled={!input.trim()||loading||remaining<=0} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-3 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">{loading?<RefreshCw className="h-3.5 w-3.5 animate-spin"/>:<Send className="h-3.5 w-3.5"/>} Ask</button></form>
  <p className="mt-2 text-[9px] text-slate-400">Free allowance is an AHVIQ app limit. Gemini also enforces project-level rate limits. AI guidance is informational, not regulated financial advice.</p>
 </section>;
};
