import { useEffect, useMemo, useState } from 'react';
import { Users, UserPlus, Copy, Check, ShieldCheck, LogOut, Trash2, CalendarDays, ChevronLeft, ChevronRight } from 'lucide-react';
import { collection, deleteDoc, doc, getDoc, getDocs, onSnapshot, setDoc, updateDoc } from 'firebase/firestore';
import { firebaseAuth, firestore } from '../services/firebase';
import { subscribeToUserData } from '../services/firestoreData';
import { subscribeToPortfolio } from '../services/portfolioService';

interface FamilyPageProps { userName:string; email:string; mode?:'dashboard'|'settings'; }
type Role='owner'|'member'|'viewer';
type FamilyMember={name:string;email:string;role:Role;joinedAt:number};
type FamilyDoc={name:string;ownerId:string;memberIds:string[];members:Record<string,FamilyMember>;createdAt:number;acceptedInviteCode?:string};
type FamilyPeriod={start:string;end:string;income:number;spending:number;savings:number};
type FamilySummary={name:string;email:string;income:number;spending:number;savings:number;netWorth:number;updatedAt:number;cycleDay?:number;periods?:Record<string,FamilyPeriod>};

const familyLinkDoc=(uid:string)=>doc(firestore,'users',uid,'family','link');
const familyDoc=(id:string)=>doc(firestore,'families',id);
const summariesCollection=(id:string)=>collection(firestore,'families',id,'summaries');
const inviteDoc=(code:string)=>doc(firestore,'familyInvites',code);
const makeId=(prefix:string)=>`${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`;
const makeCode=()=>Math.random().toString(36).slice(2,8).toUpperCase();
const money=(value:number)=>`₹${Math.round(value).toLocaleString('en-IN')}`;
const pad=(n:number)=>String(n).padStart(2,'0');
const monthKeyFromDate=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}`;
const shiftMonthKey=(key:string,delta:number)=>{const [y,m]=key.split('-').map(Number);const d=new Date(y,m-1+delta,1);return monthKeyFromDate(d);};
const dateString=(d:Date)=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const getFinancialCycle=(monthKey:string,incomeDay:number)=>{const [year,month]=monthKey.split('-').map(Number);const day=Math.min(31,Math.max(1,incomeDay));const end=new Date(year,month-1,Math.min(day-1,new Date(year,month,0).getDate()));const start=new Date(end);start.setMonth(start.getMonth()-1);start.setDate(day);return {start:dateString(start),end:dateString(end)};};
const formatDate=(v:string)=>{if(!v)return '';const [y,m,d]=v.split('-').map(Number);return new Date(y,m-1,d).toLocaleDateString('en-IN',{day:'2-digit',month:'short'});};
const formatMonth=(v:string)=>{const [y,m]=v.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-IN',{month:'long',year:'numeric'});};
const readIncomeDay=()=>{try{const raw=localStorage.getItem('finbook-settings');const p=raw?JSON.parse(raw):null;return Math.min(31,Math.max(1,Number(p?.incomeDay)||25));}catch{return 25;}};

function buildPeriods(incomes:{date:string;amount:number}[],expenses:{date:string;amount:number}[],incomeDay:number,currentMonth:string){const periods:Record<string,FamilyPeriod>={};for(let i=0;i<12;i++){const key=shiftMonthKey(currentMonth,-i);const cycle=getFinancialCycle(key,incomeDay);const income=incomes.filter(x=>x.date>=cycle.start&&x.date<=cycle.end).reduce((s,x)=>s+x.amount,0);const spending=expenses.filter(x=>x.date>=cycle.start&&x.date<=cycle.end).reduce((s,x)=>s+x.amount,0);periods[key]={start:cycle.start,end:cycle.end,income,spending,savings:income-spending};}return periods;}

export function FamilyPage({userName,email,mode='settings'}:FamilyPageProps){
  const uid=firebaseAuth.currentUser?.uid||'';
  const [familyId,setFamilyId]=useState('');const [family,setFamily]=useState<FamilyDoc|null>(null);const [summaries,setSummaries]=useState<FamilySummary[]>([]);
  const [inviteEmail,setInviteEmail]=useState('');const [inviteCode,setInviteCode]=useState('');const [joinCode,setJoinCode]=useState('');const [familyName,setFamilyName]=useState('Our Family');
  const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [copied,setCopied]=useState(false);const [incomeDay,setIncomeDay]=useState(25);const [monthKey,setMonthKey]=useState(monthKeyFromDate(new Date()));

  useEffect(()=>setIncomeDay(readIncomeDay()),[]);
  useEffect(()=>{if(!uid)return;return onSnapshot(familyLinkDoc(uid),s=>setFamilyId(String(s.data()?.familyId||'')));},[uid]);
  useEffect(()=>{if(!familyId){setFamily(null);setSummaries([]);return;}const a=onSnapshot(familyDoc(familyId),s=>setFamily(s.exists()?s.data() as FamilyDoc:null));const b=onSnapshot(summariesCollection(familyId),s=>setSummaries(s.docs.map(d=>d.data() as FamilySummary)));return()=>{a();b();};},[familyId]);
  useEffect(()=>{if(!uid||!familyId)return;let stopData=()=>{};let stopPortfolio=()=>{};const currentMonth=monthKeyFromDate(new Date());stopData=subscribeToUserData(uid,data=>{const periods=buildPeriods(data.incomes,data.expenses,incomeDay,currentMonth);const current=periods[currentMonth]||{income:0,spending:0,savings:0,start:'',end:''};void setDoc(doc(firestore,'families',familyId,'summaries',uid),{name:userName,email,income:current.income,spending:current.spending,savings:current.savings,periods,cycleDay:incomeDay,updatedAt:Date.now()},{merge:true});});stopPortfolio=subscribeToPortfolio(uid,data=>{const assets=data.fields.reduce((s,f)=>s+(Number(f.amount)||0),0);const netWorth=(data.netWorthItems||[]).reduce((s,item)=>s+(item.kind==='liability'?-Number(item.amount):Number(item.amount)),0)||assets;void setDoc(doc(firestore,'families',familyId,'summaries',uid),{name:userName,email,netWorth,updatedAt:Date.now()},{merge:true});});return()=>{stopData();stopPortfolio();};},[uid,familyId,userName,email,incomeDay]);

  const totals=useMemo(()=>summaries.reduce((a,s)=>{const p=s.periods?.[monthKey]||(monthKey===monthKeyFromDate(new Date())?{income:s.income||0,spending:s.spending||0,savings:s.savings||0}:{income:0,spending:0,savings:0});return {income:a.income+p.income,spending:a.spending+p.spending,savings:a.savings+p.savings,netWorth:a.netWorth+(s.netWorth||0)};},{income:0,spending:0,savings:0,netWorth:0}),[summaries,monthKey]);
  const role=family?.members?.[uid]?.role||'member';const cycle=getFinancialCycle(monthKey,incomeDay);const todayMonth=monthKeyFromDate(new Date());const canNext=shiftMonthKey(monthKey,1)<=todayMonth;

  const createFamily=async()=>{if(!uid)return;setBusy(true);setMessage('');const id=makeId('fam');const name=familyName.trim()||'Our Family';const member:FamilyMember={name:userName,email,role:'owner',joinedAt:Date.now()};try{await setDoc(familyDoc(id),{name,ownerId:uid,memberIds:[uid],members:{[uid]:member},createdAt:Date.now()});await setDoc(familyLinkDoc(uid),{familyId:id,role:'owner',updatedAt:Date.now()});setMessage('Family created. You can now invite a member.');}catch(e:any){setMessage(e?.message||'Could not create family.');}finally{setBusy(false);}};
  const invite=async()=>{const target=inviteEmail.trim().toLowerCase();if(!familyId||!family||role!=='owner'){setMessage('Only the family owner can invite members.');return;}if(!target||!target.includes('@')){setMessage('Enter a valid email address.');return;}if(Object.values(family.members||{}).some(m=>m.email.toLowerCase()===target)){setMessage('That email is already in the family.');return;}setBusy(true);setMessage('');const code=makeCode();try{await setDoc(inviteDoc(code),{familyId,ownerId:uid,inviteeEmail:target,role:'member',status:'pending',createdAt:Date.now(),expiresAt:Date.now()+7*24*60*60*1000});setInviteCode(code);setInviteEmail('');setMessage('Invite created. Share this code with your family member.');}catch(e:any){setMessage(e?.message||'Could not create invite.');}finally{setBusy(false);}};
  const joinFamily=async()=>{const code=joinCode.trim().toUpperCase();if(!uid||!code){setMessage('Enter the invite code.');return;}setBusy(true);setMessage('');try{const inv=await getDoc(inviteDoc(code));if(!inv.exists())throw new Error('Invite code not found.');const d=inv.data();if(d.status!=='pending')throw new Error('This invite has already been used.');if(Number(d.expiresAt||0)<Date.now())throw new Error('This invite has expired.');if(String(d.inviteeEmail||'').toLowerCase()!==(email||'').toLowerCase())throw new Error('This invite was created for a different email address.');const targetId=String(d.familyId);const target=await getDoc(familyDoc(targetId));if(!target.exists())throw new Error('Family no longer exists.');const f=target.data() as FamilyDoc;if(f.memberIds.includes(uid))throw new Error('You are already in this family.');const member:FamilyMember={name:userName,email,role:'member',joinedAt:Date.now()};await updateDoc(inviteDoc(code),{status:'accepted',acceptedBy:uid,acceptedAt:Date.now()});await updateDoc(familyDoc(targetId),{memberIds:[...f.memberIds,uid],members:{...f.members,[uid]:member},acceptedInviteCode:code});await setDoc(familyLinkDoc(uid),{familyId:targetId,role:'member',updatedAt:Date.now()});setJoinCode('');setMessage(`Joined ${f.name}.`);}catch(e:any){setMessage(e?.message||'Could not join family.');}finally{setBusy(false);}};
  const leaveFamily=async()=>{if(!familyId||!family||role==='owner'){setMessage('The family owner must transfer ownership before leaving.');return;}if(!confirm(`Leave ${family.name}? Your personal transactions will remain private.`))return;setBusy(true);try{const members={...family.members};delete members[uid];await updateDoc(familyDoc(familyId),{memberIds:family.memberIds.filter(id=>id!==uid),members});await setDoc(familyLinkDoc(uid),{familyId:'',role:'',updatedAt:Date.now()});setMessage('You left the family.');}catch(e:any){setMessage(e?.message||'Could not leave family.');}finally{setBusy(false);}};
  const deleteFamily=async()=>{if(!familyId||!family||role!=='owner'){setMessage('Only the family owner can delete the family.');return;}if(!confirm(`Delete ${family.name}? This removes the family dashboard and shared summaries. Your personal transactions, income and portfolio will not be deleted.`))return;setBusy(true);try{const snap=await getDocs(summariesCollection(familyId));await Promise.all(snap.docs.map(d=>deleteDoc(d.ref)));await deleteDoc(familyDoc(familyId));await setDoc(familyLinkDoc(uid),{familyId:'',role:'',updatedAt:Date.now()});setFamilyId('');setFamily(null);setSummaries([]);setInviteCode('');setMessage('Family deleted. Your personal financial data is unchanged.');}catch(e:any){setMessage(e?.message||'Could not delete family.');}finally{setBusy(false);}};
  const copyCode=async()=>{if(!inviteCode)return;try{await navigator.clipboard.writeText(inviteCode);setCopied(true);window.setTimeout(()=>setCopied(false),1800);}catch{setMessage(`Invite code: ${inviteCode}`);}};

  if(!familyId)return <section className="bg-white rounded-2xl border p-4 sm:p-5 overflow-hidden"><div className="flex items-start gap-3 mb-5"><div className="h-10 w-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><Users className="h-5 w-5"/></div><div><h2 className="font-bold">Family</h2><p className="text-xs text-slate-500 mt-1">Create a shared household view without exposing personal transactions.</p></div></div><div className="grid grid-cols-1 lg:grid-cols-2 gap-4"><div className="rounded-xl border bg-slate-50 p-4"><p className="font-semibold">Start a family</p><p className="text-xs text-slate-500 mt-1">You remain the owner and decide who joins.</p><input value={familyName} onChange={e=>setFamilyName(e.target.value)} className="mt-3 w-full rounded-lg border bg-white px-3 py-2.5 text-sm" placeholder="Family name"/><button disabled={busy} onClick={()=>void createFamily()} className="mt-3 w-full rounded-lg bg-slate-900 text-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50">{busy?'Creating…':'Create family'}</button></div><div className="rounded-xl border p-4"><p className="font-semibold">Join a family</p><p className="text-xs text-slate-500 mt-1">Use the code shared with your account email.</p><input value={joinCode} onChange={e=>setJoinCode(e.target.value.toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,6))} className="mt-3 w-full rounded-lg border px-3 py-2.5 text-sm tracking-[0.2em] uppercase" placeholder="ABC123"/><button disabled={busy} onClick={()=>void joinFamily()} className="mt-3 w-full rounded-lg border bg-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50">{busy?'Joining…':'Join family'}</button></div></div><div className="mt-4 flex items-start gap-2 rounded-xl bg-emerald-50 border border-emerald-100 p-3 text-xs text-emerald-800"><ShieldCheck className="h-4 w-4 mt-0.5 shrink-0"/><span>AHVIQ shares household summaries, not your private transaction list. Your personal records stay under your own account.</span></div>{message&&<p className="mt-3 text-xs text-slate-600">{message}</p>}</section>;

  const members=Object.entries(family?.members||{}).map(([id,m])=><div key={id} className="flex items-center justify-between gap-3 rounded-xl border px-3 py-2.5"><div className="flex items-center gap-3 min-w-0"><div className="h-9 w-9 rounded-full bg-slate-100 flex items-center justify-center text-sm font-bold shrink-0">{m.name?.charAt(0)?.toUpperCase()||'?'}</div><div className="min-w-0"><p className="text-sm font-semibold truncate">{m.name}{id===uid?' (You)':''}</p><p className="text-xs text-slate-500 truncate">{m.email}</p></div></div><span className="rounded-full bg-slate-100 px-2 py-1 text-[11px] font-semibold capitalize">{m.role}</span></div>);
  return <section className="bg-white rounded-2xl border p-4 sm:p-5 overflow-hidden"><div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-3"><div className="flex items-start gap-3"><div className="h-10 w-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center"><Users className="h-5 w-5"/></div><div><h2 className="font-bold">{family?.name||'Family'}</h2><p className="text-xs text-slate-500 mt-1">{mode==='dashboard'?'Shared household dashboard':'Family settings'} · {role}</p></div></div><div className="flex items-center gap-2"><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold">{family?.memberIds.length||0} members</span>{role!=='owner'&&<button disabled={busy} onClick={()=>void leaveFamily()} className="inline-flex items-center gap-1.5 rounded-lg border px-3 py-2 text-xs font-semibold text-slate-600"><LogOut className="h-3.5 w-3.5"/>Leave</button>}</div></div>
    {mode==='dashboard'&&<><div className="mt-5 rounded-xl border bg-slate-50 p-3"><div className="flex items-center justify-between gap-2"><button onClick={()=>setMonthKey(shiftMonthKey(monthKey,-1))} className="rounded-lg border bg-white p-2 text-slate-600"><ChevronLeft className="h-4 w-4"/></button><div className="text-center min-w-0"><div className="flex items-center justify-center gap-1.5 text-sm font-semibold"><CalendarDays className="h-4 w-4 text-indigo-600"/>{formatMonth(monthKey)}</div><p className="text-xs text-slate-500 mt-1">{formatDate(cycle.start)} – {formatDate(cycle.end)} · your AHVIQ financial cycle</p></div><button disabled={!canNext} onClick={()=>setMonthKey(shiftMonthKey(monthKey,1))} className="rounded-lg border bg-white p-2 text-slate-600 disabled:opacity-40"><ChevronRight className="h-4 w-4"/></button></div></div><div className="grid grid-cols-2 lg:grid-cols-4 gap-3 mt-4"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Family income</p><p className="text-lg font-bold mt-1">{money(totals.income)}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-slate-500">Family spending</p><p className="text-lg font-bold mt-1">{money(totals.spending)}</p></div><div className="rounded-xl bg-emerald-50 p-3"><p className="text-xs text-emerald-700">Family savings</p><p className="text-lg font-bold mt-1 text-emerald-700">{money(totals.savings)}</p></div><div className="rounded-xl bg-indigo-50 p-3"><p className="text-xs text-indigo-700">Combined net worth</p><p className="text-lg font-bold mt-1 text-indigo-700">{money(totals.netWorth)}</p></div></div><p className="mt-2 text-[11px] text-slate-500">Income and spending follow each member's AHVIQ financial-cycle day. Net worth is current.</p></>}
    <div className="mt-5"><p className="text-sm font-bold">Family members</p><div className="mt-2 space-y-2">{members}</div></div>
    {role==='owner'&&<div className="mt-5 rounded-xl border bg-slate-50 p-4"><div className="flex items-start gap-3"><UserPlus className="h-5 w-5 text-indigo-600 mt-0.5"/><div className="min-w-0 flex-1"><p className="font-semibold text-sm">Invite a family member</p><p className="text-xs text-slate-500 mt-1">Invite codes are tied to the member's email and expire in 7 days.</p><div className="flex flex-col sm:flex-row gap-2 mt-3"><input value={inviteEmail} onChange={e=>setInviteEmail(e.target.value)} type="email" className="flex-1 min-w-0 rounded-lg border bg-white px-3 py-2.5 text-sm" placeholder="partner@email.com"/><button disabled={busy} onClick={()=>void invite()} className="inline-flex items-center justify-center gap-1.5 rounded-lg bg-slate-900 text-white px-4 py-2.5 text-sm font-semibold disabled:opacity-50"><UserPlus className="h-4 w-4"/>Generate invite</button></div>{inviteCode&&<div className="mt-3 flex flex-col sm:flex-row sm:items-center gap-2 rounded-lg bg-white border p-3"><div className="flex-1"><p className="text-[11px] uppercase tracking-wide text-slate-400">Invite code</p><p className="font-bold tracking-[0.25em] text-lg">{inviteCode}</p></div><button onClick={()=>void copyCode()} className="inline-flex items-center justify-center gap-1.5 rounded-lg border px-3 py-2 text-sm font-semibold">{copied?<><Check className="h-4 w-4"/>Copied</>:<><Copy className="h-4 w-4"/>Copy code</>}</button></div>}</div></div></div>}
    {role==='owner'&&mode==='settings'&&<div className="mt-5 rounded-xl border border-rose-200 bg-rose-50/60 p-4"><div className="flex items-start gap-3"><Trash2 className="h-5 w-5 text-rose-600 mt-0.5"/><div><p className="font-semibold text-sm text-rose-800">Family settings</p><p className="text-xs text-rose-700 mt-1">Delete the family and its shared summaries. Your personal transactions, income and portfolio are not deleted.</p><button disabled={busy} onClick={()=>void deleteFamily()} className="mt-3 inline-flex items-center gap-2 rounded-lg border border-rose-300 bg-white px-3 py-2 text-sm font-semibold text-rose-700 disabled:opacity-50"><Trash2 className="h-4 w-4"/>{busy?'Deleting…':'Delete family'}</button></div></div></div>}
    <div className="mt-5 flex items-start gap-2 rounded-xl bg-emerald-50 border border-emerald-100 p-3 text-xs text-emerald-800"><ShieldCheck className="h-4 w-4 mt-0.5 shrink-0"/><span>Only shared household summaries are visible to family members. Individual transactions, income entries and portfolio details remain private.</span></div>{message&&<p className="mt-3 text-xs text-slate-600">{message}</p>}
  </section>;
}
