import { useEffect, useMemo, useState } from 'react';
import { collection, deleteDoc, doc, onSnapshot, setDoc } from 'firebase/firestore';
import { Baby, Check, Pencil, Plus, Target, Trash2, X } from 'lucide-react';
import { firebaseAuth, firestore } from '../services/firebase';
import { formatCurrency } from '../utils/formatters';

type FamilyGoal = { id: string; name: string; targetAmount: number; targetDate: string; monthlyContribution: number; createdBy: string; createdAt: number; currentAmount?: number; contributions?: Record<string, number>; contributorNames?: Record<string, string> };
type FamilyGoalsProps = { familyId: string; familyName?: string; members?: Record<string, { name: string; email: string; role: string }> };
const goalsCollection = (familyId: string) => collection(firestore, 'families', familyId, 'goals');
const goalDoc = (familyId: string, goalId: string) => doc(firestore, 'families', familyId, 'goals', goalId);
const makeId = (name: string) => `family-goal-${name.toLowerCase().trim().replace(/[^a-z0-9]+/g, '-') || 'goal'}-${Date.now()}`;
const today = () => new Date().toISOString().slice(0, 10);
const money = (v: number) => formatCurrency(Math.round(Number(v) || 0));

export function FamilyGoals({ familyId, familyName = 'Our Family', members = {} }: FamilyGoalsProps) {
  const uid = firebaseAuth.currentUser?.uid || '';
  const [goals, setGoals] = useState<FamilyGoal[]>([]);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState('');
  const [open, setOpen] = useState(false);
  const [editing, setEditing] = useState<string | null>(null);
  const [draft, setDraft] = useState({ name: '', targetAmount: '', targetDate: '', monthlyContribution: '' });

  useEffect(() => { if (!familyId) return; return onSnapshot(goalsCollection(familyId), snap => setGoals(snap.docs.map(item => ({ id: item.id, ...(item.data() as Omit<FamilyGoal, 'id'>) })))); }, [familyId]);
  const sortedGoals = useMemo(() => [...goals].sort((a, b) => (a.targetDate || '').localeCompare(b.targetDate || '')), [goals]);
  const startNew = () => { setEditing(null); setDraft({ name: '', targetAmount: '', targetDate: '', monthlyContribution: '' }); setOpen(true); setMessage(''); };
  const startEdit = (goal: FamilyGoal) => { setEditing(goal.id); setDraft({ name: goal.name, targetAmount: String(goal.targetAmount), targetDate: goal.targetDate, monthlyContribution: String(goal.monthlyContribution || 0) }); setOpen(true); setMessage(''); };
  const saveGoal = async () => {
    const name = draft.name.trim(); const targetAmount = Number(draft.targetAmount); const monthlyContribution = Number(draft.monthlyContribution || 0);
    if (!name || !Number.isFinite(targetAmount) || targetAmount <= 0 || !draft.targetDate || !Number.isFinite(monthlyContribution) || monthlyContribution < 0 || !uid) { setMessage('Enter a goal name, target, date and monthly contribution.'); return; }
    setBusy(true); setMessage('');
    try { const id = editing || makeId(name); const existing = editing ? goals.find(g => g.id === editing) : undefined; await setDoc(goalDoc(familyId, id), { name, targetAmount, targetDate: draft.targetDate, monthlyContribution, createdBy: existing?.createdBy || uid, createdAt: existing?.createdAt || Date.now(), currentAmount: existing?.currentAmount || 0, contributions: existing?.contributions || {}, contributorNames: existing?.contributorNames || {}, updatedAt: Date.now() }, { merge: true }); setOpen(false); setEditing(null); setMessage(editing ? 'Family goal updated.' : 'Family goal created.'); }
    catch (e: any) { setMessage(e?.message || 'Could not save the family goal.'); } finally { setBusy(false); }
  };
  const removeGoal = async (goal: FamilyGoal) => { if (!confirm(`Delete the ${goal.name} family goal? Contributions already made will no longer be shown in AHVIQ.`)) return; setBusy(true); try { await deleteDoc(goalDoc(familyId, goal.id)); setMessage('Family goal deleted.'); } catch (e: any) { setMessage(e?.message || 'Could not delete the goal.'); } finally { setBusy(false); } };

  return <section className="mt-5 rounded-2xl border border-indigo-100 bg-gradient-to-br from-white via-indigo-50/50 to-cyan-50/50 p-4 sm:p-5 shadow-sm">
    <div className="flex flex-col gap-4">
      <div className="flex items-start justify-between gap-3"><div className="flex items-start gap-3"><div className="h-10 w-10 rounded-xl bg-indigo-100 text-indigo-600 flex items-center justify-center"><Baby className="h-5 w-5" /></div><div><p className="text-xs font-semibold uppercase tracking-wider text-indigo-600">Household planning</p><h3 className="mt-1 text-lg font-bold text-slate-900">Family Goals</h3><p className="mt-1 text-xs sm:text-sm text-slate-500">Shared goals, with every contribution attributed to the family member who made it.</p></div></div><button type="button" onClick={startNew} className="inline-flex items-center gap-1.5 rounded-xl bg-slate-900 px-3 py-2 text-xs font-bold text-white"><Plus className="h-4 w-4" /> Add goal</button></div>
      {!sortedGoals.length && <div className="rounded-xl border border-dashed border-indigo-200 bg-white/80 p-5 text-center"><Target className="mx-auto h-7 w-7 text-indigo-400" /><p className="mt-2 text-sm font-semibold text-slate-800">No family goals yet</p><p className="mt-1 text-xs text-slate-500">Create a shared goal such as Baby Fund, Home Down Payment or Family Vacation.</p></div>}
      <div className="space-y-3">{sortedGoals.map(goal => { const current = Math.max(0, Number(goal.currentAmount) || 0); const target = Math.max(1, Number(goal.targetAmount) || 1); const progress = Math.min(100, Math.round(current / target * 100)); const contributions = goal.contributions || {}; const names = goal.contributorNames || {}; const contributors = Object.entries(contributions).filter(([, amount]) => Number(amount) > 0); return <div key={goal.id} className="rounded-xl border border-slate-200 bg-white p-3 sm:p-4">
        <div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="flex items-center gap-2"><Target className="h-4 w-4 text-indigo-600 shrink-0" /><h4 className="font-bold text-slate-900 truncate">{goal.name}</h4>{progress >= 100 && <span className="rounded-full bg-emerald-50 px-2 py-0.5 text-[10px] font-bold text-emerald-700">REACHED</span>}</div><p className="mt-1 text-xs text-slate-500">Target {money(target)} · {goal.targetDate ? new Date(`${goal.targetDate}T12:00:00`).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' }) : 'No date'}</p></div><div className="flex items-center gap-1"><button type="button" onClick={() => startEdit(goal)} className="rounded-lg p-2 text-slate-400 hover:bg-slate-100"><Pencil className="h-4 w-4" /></button><button type="button" onClick={() => void removeGoal(goal)} disabled={busy} className="rounded-lg p-2 text-slate-400 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4" /></button></div></div>
        <div className="mt-3 flex items-end justify-between gap-3"><div><p className="text-xl font-bold text-slate-900 tabular-nums">{money(current)}</p><p className="text-[11px] text-slate-400">of {money(target)} contributed</p></div><p className="text-sm font-bold text-indigo-600">{progress}%</p></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500 transition-all" style={{ width: `${progress}%` }} /></div>
        <div className="mt-3 grid grid-cols-1 sm:grid-cols-3 gap-2"><div className="rounded-lg bg-slate-50 p-2.5"><p className="text-[10px] text-slate-400">Monthly family plan</p><p className="mt-0.5 text-sm font-bold text-slate-900">{money(goal.monthlyContribution || 0)}</p></div><div className="rounded-lg bg-slate-50 p-2.5"><p className="text-[10px] text-slate-400">Remaining</p><p className="mt-0.5 text-sm font-bold text-slate-900">{money(Math.max(0, target - current))}</p></div><div className="rounded-lg bg-indigo-50 p-2.5"><p className="text-[10px] text-indigo-500">Contributors</p><p className="mt-0.5 text-sm font-bold text-indigo-700">{contributors.length} member{contributors.length === 1 ? '' : 's'}</p></div></div>
        {contributors.length > 0 && <div className="mt-3 rounded-lg border border-slate-100 bg-slate-50/70 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Contribution breakdown</p><div className="mt-2 space-y-1.5">{contributors.map(([memberId, amount]) => <div key={memberId} className="flex items-center justify-between gap-2 text-xs"><span className="truncate text-slate-600">{names[memberId] || members[memberId]?.name || (memberId === uid ? 'You' : 'Family member')}</span><span className="font-bold text-slate-900 tabular-nums">{money(Number(amount))}</span></div>)}</div></div>}
      </div>; })}</div>
      {open && <div className="rounded-xl border border-indigo-200 bg-white p-4"><div className="flex items-center justify-between"><div><p className="font-bold text-slate-900">{editing ? 'Edit family goal' : 'Create family goal'}</p><p className="text-xs text-slate-500 mt-0.5">This goal is shared with {familyName}.</p></div><button type="button" onClick={() => setOpen(false)} className="rounded-lg p-1.5 text-slate-400 hover:bg-slate-100"><X className="h-4 w-4" /></button></div><div className="mt-3 grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Goal name<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm font-normal" placeholder="Baby Fund" /></label><label className="text-xs font-semibold text-slate-600">Target amount<input type="number" min="1" value={draft.targetAmount} onChange={e => setDraft({ ...draft, targetAmount: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm font-normal" placeholder="300000" /></label><label className="text-xs font-semibold text-slate-600">Target date<input type="date" min={today()} value={draft.targetDate} onChange={e => setDraft({ ...draft, targetDate: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm font-normal" /></label><label className="text-xs font-semibold text-slate-600">Monthly family contribution<input type="number" min="0" value={draft.monthlyContribution} onChange={e => setDraft({ ...draft, monthlyContribution: e.target.value })} className="mt-1 w-full rounded-lg border px-3 py-2.5 text-sm font-normal" placeholder="30000" /></label></div><div className="mt-3 flex justify-end gap-2"><button type="button" onClick={() => setOpen(false)} className="rounded-lg border px-3 py-2 text-xs font-semibold">Cancel</button><button type="button" disabled={busy} onClick={() => void saveGoal()} className="inline-flex items-center gap-1.5 rounded-lg bg-slate-900 px-4 py-2 text-xs font-bold text-white disabled:opacity-50"><Check className="h-4 w-4" /> {busy ? 'Saving…' : editing ? 'Save changes' : 'Create goal'}</button></div></div>}
      {message && <p className="text-xs text-slate-600">{message}</p>}
    </div>
  </section>;
}
