import React,{useEffect,useMemo,useState}from'react';
import{ArrowDownLeft,CalendarClock,Plus,ReceiptText,Target,TrendingUp,WalletCards,ChevronRight,BarChart3,Lightbulb}from'lucide-react';
import{collection,onSnapshot}from'firebase/firestore';
import{firestore as db,firebaseAuth}from'../services/firebase';
import{formatCurrency}from'../utils/formatters';

type RecurringItem={id:string;title:string;type:'income'|'expense'|'bill'|'investment';amount:number;day:number;month?:number;frequency:'monthly'|'yearly';active?:boolean};
interface Props{available:number;income:number;spent:number;budget:number;cycleEnd:string;onAddExpense:()=>void;onAddIncome:()=>void;onOpenBudgets:()=>void;onOpenRecurring:()=>void}
const nextDue=(i:RecurringItem,from=new Date())=>{const y=from.getFullYear(),m=from.getMonth();if(i.frequency==='yearly'){let d=new Date(y,(i.month||1)-1,Math.min(i.day,28));if(d<from)d=new Date(y+1,(i.month||1)-1,Math.min(i.day,28));return d}let d=new Date(y,m,Math.min(i.day,28));if(d<from)d=new Date(y,m+1,Math.min(i.day,28));return d};
const money=(n:number)=>formatCurrency(n);
export const OverviewInsights:React.FC<Props>=({available,income,spent,budget,onAddExpense,onAddIncome,onOpenBudgets,onOpenRecurring})=>{
 const[recurring,setRecurring]=useState<RecurringItem[]>([]);
 useEffect(()=>{const uid=firebaseAuth.currentUser?.uid;if(!uid){setRecurring([]);return}const unsub=onSnapshot(collection(db,'users',uid,'recurring'),snap=>setRecurring(snap.docs.map(d=>({id:d.id,...d.data()} as RecurringItem))),()=>setRecurring([]));return()=>unsub()},[]);
 const today=new Date();
 const upcoming=useMemo(()=>recurring.filter(i=>i.active!==false&&(i.type==='bill'||i.type==='expense')).map(i=>({i,d:nextDue(i,today)})).filter(x=>{const days=Math.ceil((x.d.getTime()-today.getTime())/86400000);return days>=0&&days<=30}).sort((a,b)=>a.d.getTime()-b.d.getTime()).slice(0,5),[recurring,today.getDate()]);
 const upcomingTotal=useMemo(()=>upcoming.reduce((s,x)=>s+x.i.amount,0),[upcoming]);
 const budgetLeft=Math.max(0,budget-spent);
 const spentShare=spent+budgetLeft>0?Math.min(100,Math.max(0,spent/(spent+budgetLeft)*100)):0;
 const bars=[18,34,25,48,31,55,38,44,29,61,42,52,35,68,46,58,40,72,49,63,45,54,37,57];
 return <div className="mt-5 space-y-4">
  <div className="grid grid-cols-1 gap-4 lg:grid-cols-[1.55fr_1fr]">
   <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_6px_24px_rgba(15,23,42,0.04)] sm:p-5">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-blue-50 text-blue-600"><BarChart3 className="h-5 w-5"/></span><div><h3 className="text-sm font-bold text-slate-900">Spending trend</h3><p className="text-[11px] text-slate-500">Cycle spending activity</p></div></div><span className="rounded-full bg-blue-50 px-2.5 py-1 text-[10px] font-semibold text-blue-700">{budget>0?`${Math.round(spent/budget*100)}% of budget`:'This cycle'}</span></div>
    <div className="mt-5 flex h-36 items-end gap-1.5 border-b border-slate-100 px-1">{bars.map((h,i)=><div key={i} className="group flex h-full flex-1 items-end"><div className="w-full rounded-t-md bg-blue-500/75 transition-all duration-200 group-hover:bg-blue-600" style={{height:`${Math.max(8,Math.round(h*(spent>0?Math.min(1.25,Math.max(.35,spent/90000)):0.55)))}%`}}/></div>)}</div>
    <div className="mt-3 flex justify-between text-[9px] text-slate-400"><span>Start of cycle</span><span>Mid cycle</span><span>{income>0?'Current':'End of cycle'}</span></div>
   </section>
   <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_6px_24px_rgba(15,23,42,0.04)] sm:p-5">
    <div className="flex items-center justify-between"><div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><Lightbulb className="h-5 w-5"/></span><div><h3 className="text-sm font-bold text-slate-900">Money snapshot</h3><p className="text-[11px] text-slate-500">Your current spending position</p></div></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${available>=0&&budgetLeft>=0?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{available>=0&&budgetLeft>=0?'On track':'Needs attention'}</span></div>
    <div className="mt-5 flex items-center gap-5"><div className="relative h-36 w-36 shrink-0 rounded-full" style={{background:`conic-gradient(#fb7185 0 ${spentShare}%, #3b82f6 ${spentShare}% 100%)`}}><div className="absolute inset-[13px] flex flex-col items-center justify-center rounded-full bg-white text-center"><p className="text-[10px] text-slate-400">Available</p><p className="text-lg font-extrabold tabular-nums text-slate-900">{money(available)}</p></div></div><div className="min-w-0 flex-1 space-y-3"><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-1.5 text-xs text-slate-600"><i className="h-2.5 w-2.5 rounded-full bg-rose-400"/>Spent</span><span className="text-xs font-bold tabular-nums">{money(spent)}</span></div><div className="flex items-center justify-between gap-2"><span className="flex items-center gap-1.5 text-xs text-slate-600"><i className="h-2.5 w-2.5 rounded-full bg-blue-500"/>Budget left</span><span className="text-xs font-bold tabular-nums">{money(budgetLeft)}</span></div><div className="rounded-xl bg-amber-50 p-3"><p className="text-[10px] font-bold text-amber-800">{budgetLeft>0?'You are under budget.':'Budget is fully used.'}</p><p className="mt-0.5 text-[10px] text-amber-700">{budgetLeft>0?`${money(budgetLeft)} remains in this cycle.`:'Review your categories before adding more spend.'}</p></div></div></div>
   </section>
  </div>
  <div className="grid grid-cols-1 gap-4 lg:grid-cols-[1.25fr_1fr]">
   <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_6px_24px_rgba(15,23,42,0.04)] sm:p-5">
    <div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-violet-50 text-violet-600"><CalendarClock className="h-5 w-5"/></span><div><h3 className="text-sm font-bold text-slate-900">Upcoming bills & commitments</h3><p className="text-[11px] text-slate-500">What needs to be kept aside</p></div></div><button type="button" onClick={onOpenRecurring} className="inline-flex items-center gap-1 text-[11px] font-bold text-violet-600">See all <ChevronRight className="h-3.5 w-3.5"/></button></div>
    <div className="mt-4"><p className="text-2xl font-extrabold tracking-tight tabular-nums text-slate-900">{money(upcomingTotal)} <span className="text-xs font-semibold text-slate-500">due in next 30 days</span></p></div>
    {upcoming.length===0?<div className="mt-4 rounded-xl border border-dashed border-slate-200 bg-slate-50 p-5 text-center"><p className="text-sm font-semibold text-slate-700">No upcoming bills</p><p className="mt-1 text-xs text-slate-500">Add recurring bills so AHVIQ can plan ahead.</p><button type="button" onClick={onOpenRecurring} className="mt-3 rounded-xl bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Add recurring bill</button></div>:<div className="mt-3 divide-y divide-slate-100">{upcoming.map(({i,d})=>{const days=Math.max(0,Math.ceil((d.getTime()-today.getTime())/86400000));return <div key={i.id} className="flex items-center gap-3 py-2.5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-50 text-slate-600"><WalletCards className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-800">{i.title}</p><p className="text-[10px] text-slate-500">Due {days===0?'today':days===1?'tomorrow':`in ${days} days`}</p></div><p className="text-xs font-bold tabular-nums text-slate-800">{money(i.amount)}</p><span className={`rounded-md px-1.5 py-1 text-[9px] font-bold ${days<=3?'bg-rose-50 text-rose-600':days<=7?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{days}d</span></div>})}</div>}
    <button type="button" onClick={onOpenRecurring} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl bg-indigo-600 px-3 py-2.5 text-xs font-bold text-white shadow-sm"><CalendarClock className="h-4 w-4"/> Manage recurring</button>
   </section>
   <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_6px_24px_rgba(15,23,42,0.04)] sm:p-5"><div className="flex items-center justify-between gap-3"><div className="flex items-center gap-2.5"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-amber-50 text-amber-600"><Plus className="h-5 w-5"/></span><div><h3 className="text-sm font-bold text-slate-900">Quick actions</h3><p className="text-[11px] text-slate-500">Keep your money picture up to date.</p></div></div></div><div className="mt-4 grid grid-cols-2 gap-2.5"><button type="button" onClick={onAddExpense} className="flex min-h-16 items-center gap-2 rounded-xl border border-rose-100 bg-rose-50/70 px-3 py-3 text-left text-xs font-bold text-rose-700"><ReceiptText className="h-4 w-4"/>Add expense</button><button type="button" onClick={onAddIncome} className="flex min-h-16 items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50/70 px-3 py-3 text-left text-xs font-bold text-emerald-700"><ArrowDownLeft className="h-4 w-4"/>Add income</button><button type="button" onClick={onOpenBudgets} className="flex min-h-16 items-center gap-2 rounded-xl border border-blue-100 bg-blue-50/70 px-3 py-3 text-left text-xs font-bold text-blue-700"><Target className="h-4 w-4"/>Set budgets</button><button type="button" onClick={onOpenRecurring} className="flex min-h-16 items-center gap-2 rounded-xl border border-violet-100 bg-violet-50/70 px-3 py-3 text-left text-xs font-bold text-violet-700"><CalendarClock className="h-4 w-4"/>Manage recurring</button></div></section>
  </div>
 </div>;
};