import React,{useEffect,useMemo,useState}from'react';
import{ArrowDownLeft,CalendarClock,Plus,ReceiptText,Target,TrendingUp,WalletCards,ChevronRight}from'lucide-react';
import{collection,onSnapshot}from'firebase/firestore';
import{firestore as db,firebaseAuth}from'../services/firebase';
import{formatCurrency}from'../utils/formatters';

type RecurringItem={id:string;title:string;type:'income'|'expense'|'bill'|'investment';amount:number;day:number;month?:number;frequency:'monthly'|'yearly';active?:boolean};
interface Props{available:number;income:number;spent:number;budget:number;cycleEnd:string;onAddExpense:()=>void;onAddIncome:()=>void;onOpenBudgets:()=>void;onOpenRecurring:()=>void}
const nextDue=(i:RecurringItem,from=new Date())=>{const y=from.getFullYear(),m=from.getMonth();if(i.frequency==='yearly'){let d=new Date(y,(i.month||1)-1,Math.min(i.day,28));if(d<from)d=new Date(y+1,(i.month||1)-1,Math.min(i.day,28));return d}let d=new Date(y,m,Math.min(i.day,28));if(d<from)d=new Date(y,m+1,Math.min(i.day,28));return d};
const money=(n:number)=>formatCurrency(n);
export const OverviewInsights:React.FC<Props>=({available,income,spent,budget,onAddExpense,onAddIncome,onOpenBudgets,onOpenRecurring})=>{
 const[recurring,setRecurring]=useState<RecurringItem[]>([]);
 useEffect(()=>{const uid=firebaseAuth.currentUser?.uid;if(!uid){setRecurring([]);return}const unsub=onSnapshot(collection(db,'users',uid,'recurring'),snap=>setRecurring(snap.docs.map(d=>({id:d.id,...d.data()} as RecurringItem))),()=>setRecurring([]));return()=>unsub()},[]);
 const today=new Date();
 const upcoming=useMemo(()=>recurring.filter(i=>i.active!==false&&(i.type==='bill'||i.type==='expense')).map(i=>({i,d:nextDue(i,today)})).filter(x=>{const days=Math.ceil((x.d.getTime()-today.getTime())/86400000);return days>=0&&days<=30}).sort((a,b)=>a.d.getTime()-b.d.getTime()).slice(0,5),[recurring,today.getDate()]);
 const upcomingTotal=useMemo(()=>recurring.filter(i=>i.active!==false&&(i.type==='bill'||i.type==='expense')).map(i=>({i,d:nextDue(i,today)})).filter(x=>{const days=Math.ceil((x.d.getTime()-today.getTime())/86400000);return days>=0&&days<=30}).reduce((s,x)=>s+x.i.amount,0),[recurring,today.getDate()]);
 const daysUntil=(d:Date)=>Math.max(0,Math.ceil((d.getTime()-today.getTime())/86400000));
 const hasIncome=income>0;const budgetLeft=budget-spent;
 return <div className="mt-4 space-y-4">
  <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
   <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5 shadow-[0_1px_3px_rgba(15,23,42,0.04)]">
    <div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600"><CalendarClock className="h-5 w-5"/></span><div><h3 className="text-sm font-bold text-slate-900">Upcoming bills & commitments</h3><p className="text-[11px] text-slate-500">What needs to be kept aside</p></div></div><button type="button" onClick={onOpenRecurring} className="inline-flex items-center gap-1 text-[11px] font-bold text-indigo-600">See all <ChevronRight className="h-3.5 w-3.5"/></button></div>
    <div className="mt-4"><p className="text-2xl font-bold tracking-tight tabular-nums text-slate-900">{money(upcomingTotal)} <span className="text-xs font-semibold text-slate-500">due in next 30 days</span></p></div>
    {upcoming.length===0?<div className="mt-4 rounded-xl bg-slate-50 px-3 py-4 text-center"><p className="text-sm font-semibold text-slate-700">No upcoming bills</p><p className="mt-1 text-xs text-slate-500">Add recurring bills so AHVIQ can plan ahead.</p><button type="button" onClick={onOpenRecurring} className="mt-3 rounded-lg bg-indigo-600 px-3 py-2 text-xs font-bold text-white">Add recurring bill</button></div>:<div className="mt-3 divide-y divide-slate-100">{upcoming.map(({i,d})=>{const days=daysUntil(d);return <div key={i.id} className="flex items-center gap-3 py-2.5"><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-50 text-slate-600"><WalletCards className="h-4 w-4"/></span><div className="min-w-0 flex-1"><p className="truncate text-xs font-semibold text-slate-800">{i.title}</p><p className="text-[10px] text-slate-500">Due {days===0?'today':days===1?'tomorrow':`in ${days} days`}</p></div><p className="text-xs font-bold tabular-nums text-slate-800">{money(i.amount)}</p><span className={`rounded-md px-1.5 py-1 text-[9px] font-bold ${days<=3?'bg-rose-50 text-rose-600':days<=7?'bg-amber-50 text-amber-700':'bg-slate-100 text-slate-600'}`}>{days}d</span></div>})}</div>}
    <button type="button" onClick={onOpenRecurring} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-indigo-100 bg-indigo-50/50 px-3 py-2.5 text-xs font-bold text-indigo-700"><CalendarClock className="h-4 w-4"/> Manage recurring</button>
   </section>
   <section className="rounded-2xl border border-slate-200 bg-white p-4 sm:p-5 shadow-[0_1px_3px_rgba(15,23,42,0.04)]">
    <div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-slate-900">Money snapshot</h3><p className="text-[11px] text-slate-500">Your current spending position</p></div><span className={`rounded-full px-2.5 py-1 text-[10px] font-bold ${available>=0&&budgetLeft>=0?'bg-emerald-50 text-emerald-700':'bg-rose-50 text-rose-700'}`}>{available>=0&&budgetLeft>=0?'On track':'Needs attention'}</span></div>
    <div className="mt-4 grid grid-cols-2 gap-2"><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Available</p><p className="mt-1 text-lg font-bold tabular-nums">{money(available)}</p></div><div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400">Budget left</p><p className={`mt-1 text-lg font-bold tabular-nums ${budgetLeft<0?'text-rose-600':'text-slate-900'}`}>{budget>0?money(Math.max(0,budgetLeft)):'Not set'}</p></div></div>
    {!hasIncome&&<div className="mt-3 flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50/60 p-3"><TrendingUp className="h-4 w-4 shrink-0 text-emerald-600"/><p className="text-[11px] text-emerald-800"><span className="font-bold">Start with income.</span> Add salary or regular income to make your money picture meaningful.</p></div>}
   </section>
  </div>
  <section className="rounded-2xl border border-slate-200 bg-white p-4 shadow-[0_1px_3px_rgba(15,23,42,0.04)]"><div className="flex items-center justify-between gap-3"><div><h3 className="text-sm font-bold text-slate-900">Quick actions</h3><p className="mt-0.5 text-[11px] text-slate-500">Keep your money picture up to date.</p></div><Plus className="h-4 w-4 text-slate-400"/></div><div className="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-4"><button type="button" onClick={onAddExpense} className="flex items-center gap-2 rounded-xl border border-rose-100 bg-rose-50/60 px-3 py-3 text-left text-xs font-semibold text-rose-700"><ReceiptText className="h-4 w-4"/> Add expense</button><button type="button" onClick={onAddIncome} className="flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50/60 px-3 py-3 text-left text-xs font-semibold text-emerald-700"><ArrowDownLeft className="h-4 w-4"/> Add income</button><button type="button" onClick={onOpenBudgets} className="flex items-center gap-2 rounded-xl border border-sky-100 bg-sky-50/60 px-3 py-3 text-left text-xs font-semibold text-sky-700"><Target className="h-4 w-4"/> Set budgets</button><button type="button" onClick={onOpenRecurring} className="flex items-center gap-2 rounded-xl border border-violet-100 bg-violet-50/60 px-3 py-3 text-left text-xs font-semibold text-violet-700"><CalendarClock className="h-4 w-4"/> Manage recurring</button></div></section>
 </div>;
};