import React, { useEffect, useMemo, useState } from 'react';
import { Bell, Banknote, CalendarClock, CheckCircle2, Pencil, Plus, Trash2, X } from 'lucide-react';

export interface RecurringItem { id:string; title:string; type:'income'|'expense'|'bill'; amount:number; day:number; frequency:'monthly'|'yearly'; autoRecord:boolean; reminder:boolean; active:boolean; }
interface Props { userId?: string; }
const blank:Omit<RecurringItem,'id'>={title:'',type:'expense',amount:0,day:1,frequency:'monthly',autoRecord:true,reminder:true,active:true};
const money=(n:number)=>`₹${n.toLocaleString('en-IN',{maximumFractionDigits:0})}`;
const storageKey=(uid?:string)=>`finbook-recurring-${uid||'local'}-v1`;
export const RecurringBillsPage:React.FC<Props>=({userId})=>{
 const [items,setItems]=useState<RecurringItem[]>([]),[editing,setEditing]=useState<RecurringItem|null>(null),[form,setForm]=useState<Omit<RecurringItem,'id'>>(blank),[show,setShow]=useState(false),[error,setError]=useState('');
 useEffect(()=>{try{const raw=localStorage.getItem(storageKey(userId));if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed))setItems(parsed);}}catch{}},[userId]);
 const persist=(next:RecurringItem[])=>{setItems(next);try{localStorage.setItem(storageKey(userId),JSON.stringify(next));}catch{}};
 const open=(item?:RecurringItem)=>{setEditing(item||null);setForm(item?{...item}:blank);setError('');setShow(true)};
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.title.trim()){setError('Enter a name for this recurring item.');return;}if(!Number.isFinite(form.amount)||form.amount<=0){setError('Enter an amount greater than ₹0.');return;}const item={...form,amount:Math.round(form.amount*100)/100,id:editing?.id||`rec-${Date.now()}`};persist(editing?items.map(i=>i.id===item.id?item:i):[...items,item]);setShow(false)};
 const remove=(id:string)=>{if(confirm('Delete this recurring item?'))persist(items.filter(i=>i.id!==id));};
 const monthlyOutflow=useMemo(()=>items.filter(i=>i.active&&i.frequency==='monthly'&&i.type!=='income').reduce((s,i)=>s+i.amount,0),[items]);
 const monthlyIncome=useMemo(()=>items.filter(i=>i.active&&i.frequency==='monthly'&&i.type==='income').reduce((s,i)=>s+i.amount,0),[items]);
 const recurringBalance=monthlyIncome-monthlyOutflow;
 return <div className="space-y-4"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Recurring & Bills</h2><p className="text-sm text-slate-500">Automate regular income, expenses and payment reminders.</p></div><button onClick={()=>open()} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Add</button></div>
 <div className="grid grid-cols-2 lg:grid-cols-3 gap-3"><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">Monthly commitments</p><p className="mt-1 text-xl font-bold">{money(monthlyOutflow)}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">Monthly income</p><p className="mt-1 text-xl font-bold text-emerald-600">{money(monthlyIncome)}</p></div><div className="col-span-2 lg:col-span-1 rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">Recurring balance</p><p className={`mt-1 text-xl font-bold ${recurringBalance<0?'text-rose-600':'text-slate-900'}`}>{money(recurringBalance)}</p><p className="mt-0.5 text-[11px] text-slate-400">Income minus recurring outflows</p></div></div>
 <div className="flex items-center justify-between px-1"><p className="text-xs font-semibold text-slate-500">{items.filter(i=>i.active).length} active item{items.filter(i=>i.active).length===1?'':'s'}</p><p className="text-xs text-slate-400">Auto-recording: {items.filter(i=>i.active&&i.autoRecord).length}</p></div>
 <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="divide-y divide-slate-100">{items.length===0?<div className="p-8 text-center text-sm text-slate-500">No recurring items yet. Add salary, SIPs, rent, EMIs or bills.</div>:items.map(item=><div key={item.id} className="flex items-center gap-3 p-4"><div className={`h-10 w-10 shrink-0 rounded-xl flex items-center justify-center ${item.type==='income'?'bg-emerald-50 text-emerald-600':item.type==='bill'?'bg-amber-50 text-amber-600':'bg-indigo-50 text-indigo-600'}`}>{item.type==='income'?<Banknote className="h-5 w-5"/>:item.type==='bill'?<Bell className="h-5 w-5"/>:<CalendarClock className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><p className="font-semibold truncate">{item.title}</p><p className="text-xs text-slate-500">{item.frequency==='monthly'?'Every month':'Every year'} · Day {item.day} · {item.autoRecord?'Auto-record':'Reminder only'}</p></div><p className={`font-bold tabular-nums ${item.type==='income'?'text-emerald-600':''}`}>{item.type==='income'?'+':'−'}{money(item.amount)}</p><button onClick={()=>open(item)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Pencil className="h-4 w-4"/></button><button onClick={()=>remove(item.id)} className="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>
 {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-3" onClick={e=>e.target===e.currentTarget&&setShow(false)}><form noValidate onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl space-y-4"><div className="flex justify-between"><h3 className="text-lg font-bold">{editing?'Edit':'Add'} recurring item</h3><button type="button" onClick={()=>setShow(false)}><X className="h-5 w-5"/></button></div>{error&&<div className="rounded-lg border border-rose-200 bg-rose-50 px-3 py-2 text-xs text-rose-700">{error}</div>}<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Salary, SIP, Rent, Electricity" className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"/><div className="grid grid-cols-2 gap-3"><input type="number" min="0.01" value={form.amount||''} onChange={e=>setForm({...form,amount:e.target.value===''?0:Number(e.target.value)})} placeholder="Amount" className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as RecurringItem['type']})} className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="income">Income</option><option value="expense">Expense</option><option value="bill">Bill</option></select></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Day<select aria-label="Day of month" value={form.day} onChange={e=>setForm({...form,day:Number(e.target.value)})} className="mt-1 w-full appearance-none rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm">{Array.from({length:31},(_,i)=><option key={i+1} value={i+1}>{i+1}</option>)}</select></label><label className="text-xs font-semibold text-slate-600">Frequency<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value as RecurringItem['frequency']})} className="mt-1 w-full rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.autoRecord} onChange={e=>setForm({...form,autoRecord:e.target.checked})}/><CheckCircle2 className="h-4 w-4 text-indigo-600"/>Automatically record transaction</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.reminder} onChange={e=>setForm({...form,reminder:e.target.checked})}/><Bell className="h-4 w-4 text-amber-500"/>Remind me</label><div className="flex gap-2 justify-end pt-2"><button type="button" onClick={()=>setShow(false)} className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Cancel</button><button className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Save</button></div></form></div>}
 </div>;
};
