import React, { useMemo, useState } from 'react';
import { Bell, CalendarClock, CheckCircle2, CircleDollarSign, Pencil, Plus, Trash2, X } from 'lucide-react';

export interface RecurringItem {
  id: string; title: string; type: 'income' | 'expense' | 'bill'; amount: number; day: number;
  frequency: 'monthly' | 'yearly'; autoRecord: boolean; reminder: boolean; active: boolean;
}
interface Props { items: RecurringItem[]; onSave: (item: RecurringItem) => void; onDelete: (id: string) => void; }
const blank: Omit<RecurringItem,'id'> = { title:'', type:'expense', amount:0, day:1, frequency:'monthly', autoRecord:true, reminder:true, active:true };
const money=(n:number)=>`₹${n.toLocaleString('en-IN',{maximumFractionDigits:0})}`;

export const RecurringBillsPage: React.FC<Props> = ({items,onSave,onDelete}) => {
 const [editing,setEditing]=useState<RecurringItem|null>(null); const [form,setForm]=useState<Omit<RecurringItem,'id'>>(blank); const [show,setShow]=useState(false);
 const open=(item?:RecurringItem)=>{setEditing(item||null);setForm(item?{...item}:blank);setShow(true)};
 const submit=(e:React.FormEvent)=>{e.preventDefault();if(!form.title.trim()||form.amount<=0)return;onSave({...form,id:editing?.id||`rec-${Date.now()}`});setShow(false)};
 const monthly=useMemo(()=>items.filter(i=>i.active&&i.frequency==='monthly').reduce((s,i)=>s+i.amount,0),[items]);
 return <div className="space-y-4">
  <div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold">Recurring & Bills</h2><p className="text-sm text-slate-500">Automate regular income, expenses and payment reminders.</p></div><button onClick={()=>open()} className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-3.5 py-2.5 text-sm font-semibold text-white"><Plus className="h-4 w-4"/>Add</button></div>
  <div className="grid grid-cols-2 lg:grid-cols-3 gap-3"><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">Monthly commitments</p><p className="mt-1 text-xl font-bold">{money(monthly)}</p></div><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">Active items</p><p className="mt-1 text-xl font-bold">{items.filter(i=>i.active).length}</p></div><div className="hidden lg:block rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-semibold text-slate-500">Auto-recording</p><p className="mt-1 text-xl font-bold">{items.filter(i=>i.active&&i.autoRecord).length}</p></div></div>
  <div className="rounded-2xl border border-slate-200 bg-white overflow-hidden"><div className="divide-y divide-slate-100">{items.length===0?<div className="p-8 text-center text-sm text-slate-500">No recurring items yet. Add salary, SIPs, rent, EMIs or bills.</div>:items.map(item=><div key={item.id} className="flex items-center gap-3 p-4"><div className={`h-10 w-10 shrink-0 rounded-xl flex items-center justify-center ${item.type==='income'?'bg-emerald-50 text-emerald-600':item.type==='bill'?'bg-amber-50 text-amber-600':'bg-indigo-50 text-indigo-600'}`}>{item.type==='income'?<CircleDollarSign className="h-5 w-5"/>:item.type==='bill'?<Bell className="h-5 w-5"/>:<CalendarClock className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><p className="font-semibold truncate">{item.title}</p><p className="text-xs text-slate-500">{item.frequency==='monthly'?'Every month':'Every year'} · Day {item.day} · {item.autoRecord?'Auto-record':'Reminder only'}</p></div><p className={`font-bold tabular-nums ${item.type==='income'?'text-emerald-600':''}`}>{item.type==='income'?'+':'−'}{money(item.amount)}</p><button onClick={()=>open(item)} className="rounded-lg p-2 text-slate-500 hover:bg-slate-100"><Pencil className="h-4 w-4"/></button><button onClick={()=>onDelete(item.id)} className="rounded-lg p-2 text-slate-500 hover:bg-rose-50 hover:text-rose-600"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>
  {show&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/50 p-3" onClick={e=>e.target===e.currentTarget&&setShow(false)}><form onSubmit={submit} className="w-full max-w-md rounded-2xl bg-white p-5 shadow-xl space-y-4"><div className="flex justify-between"><h3 className="text-lg font-bold">{editing?'Edit':'Add'} recurring item</h3><button type="button" onClick={()=>setShow(false)}><X className="h-5 w-5"/></button></div><input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="Salary, SIP, Rent, Electricity" className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"/><div className="grid grid-cols-2 gap-3"><input required type="number" min="0.01" value={form.amount||''} onChange={e=>setForm({...form,amount:Number(e.target.value)})} placeholder="Amount" className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value as RecurringItem['type']})} className="w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="income">Income</option><option value="expense">Expense</option><option value="bill">Bill</option></select></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">Day<input type="number" min="1" max="31" value={form.day} onChange={e=>setForm({...form,day:Math.min(31,Math.max(1,Number(e.target.value)))})} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"/></label><label className="text-xs font-semibold text-slate-600">Frequency<select value={form.frequency} onChange={e=>setForm({...form,frequency:e.target.value as RecurringItem['frequency']})} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.autoRecord} onChange={e=>setForm({...form,autoRecord:e.target.checked})}/><CheckCircle2 className="h-4 w-4 text-indigo-600"/>Automatically record transaction</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.reminder} onChange={e=>setForm({...form,reminder:e.target.checked})}/><Bell className="h-4 w-4 text-amber-500"/>Remind me</label><div className="flex gap-2 justify-end pt-2"><button type="button" onClick={()=>setShow(false)} className="rounded-lg border px-4 py-2.5 text-sm font-semibold">Cancel</button><button className="rounded-lg bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Save</button></div></form></div>}
 </div>;
};
